// !!! This is a file automatically generated by hipify!!!
// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#pragma once

#include "ck_tile/core_hip.hpp"
#include "ck_tile/ops/softmax_hip.hpp"
#include "ck_tile/ops/topk_hip.hpp"

namespace ck_tile {

struct MoeSortingPolicy
{
};
} // namespace ck_tile
